In [2]:
import pandas as pd
import numpy as np

In [3]:
np.array([1,2,3,])

array([1, 2, 3])

In [4]:
x1 = 5
x2 = np.array([1,2,3])

In [5]:
x3 = np.zeros((100,3,5))

In [6]:
x3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
x = np.array([3,3,4])

In [8]:
x1 = 5

In [9]:
dir(x1)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [10]:
eng = np.random.randint(60,101,100)
kor = np.random.randint(60,101,100)
math = np.random.randint(60,101,100)
sci = np.random.randint(60,101,100)

In [11]:
df = pd.DataFrame()

In [12]:
eng

array([ 99,  60,  67,  63,  69,  69,  90,  77,  75,  76,  76,  92,  85,
        82,  81,  94,  97,  76, 100,  84,  75,  85,  72,  92,  96,  85,
        61,  63,  70,  98,  81, 100,  76,  95,  78,  61,  96,  62,  98,
        93,  95, 100,  61,  80,  85,  65,  63,  72,  85,  94,  98,  84,
        72,  85,  62,  91,  83,  68,  89,  85,  96, 100,  96,  72, 100,
        64,  94,  73,  91,  76,  89,  63,  78,  83,  90,  66,  71,  98,
        76,  72,  73,  68,  74,  72,  70,  99,  81,  67,  73,  71,  79,
        71,  92,  74,  86,  77,  87,  62,  65,  97])

In [13]:
df['eng'] = eng

In [14]:
df['kor'] = kor
df['math'] = math
df['sci'] = sci

In [15]:
df.to_csv("score.csv", index=None)

In [16]:
data = pd.read_csv("score.csv")

In [17]:
data['total'] = data.eng + data.kor + data.math + data.sci

In [18]:
data = data[['eng', 'kor', 'math', 'sci']]

In [19]:
np.sum(data.values, axis=1)

array([323, 299, 333, 295, 304, 297, 291, 315, 325, 298, 282, 357, 320,
       309, 305, 315, 309, 319, 366, 327, 301, 320, 302, 367, 318, 366,
       303, 321, 294, 327, 311, 344, 286, 353, 314, 307, 329, 278, 326,
       362, 314, 328, 267, 329, 306, 322, 323, 321, 367, 323, 336, 349,
       351, 309, 295, 319, 324, 350, 345, 373, 317, 329, 362, 342, 364,
       315, 364, 348, 379, 345, 321, 289, 312, 314, 334, 312, 271, 318,
       298, 305, 344, 336, 347, 335, 304, 327, 322, 332, 314, 345, 314,
       320, 347, 278, 334, 323, 313, 309, 312, 368], dtype=int64)

In [20]:
data = data[data.columns[:-1]]
data

eng  kor  math
0    99   97    62
1    60   61    97
2    67   84    89
3    63   71    90
4    69   73    79
..  ...  ...   ...
95   77   79    92
96   87   72    77
97   62   93    70
98   65   83    76
99   97  100    74

[100 rows x 3 columns]

In [21]:
data['avg'] = data.total / 4

AttributeError: 'DataFrame' object has no attribute 'total'

In [ ]:
data['best_subject'] = data.columns[np.argmax(data.iloc[:,:4].values,axis=1)]


In [ ]:
data['greade'] = np.where(data['avg'] >= 90, 'A',
np.where(data['avg'] >= 80, 'B', 
np.where(data['avg'] >= 70, 'C', 'D')))


In [ ]:
data.best_subject.value_counts()[0:1].index[0]

'eng'

In [ ]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'popul':pop})
data

area     popul
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data['density'] = data['popul'] / data['area']
data

area     popul     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [ ]:
(data.area.max() == data.area).values

array([False,  True, False, False, False])

In [ ]:
data.iloc[(data.area.max() == data.area).values, 1:]

popul   density
Texas  26448193  38.01874

In [ ]:
data.loc[data.area.max() == data.area, ['popul', 'density']]

popul   density
Texas  26448193  38.01874

In [ ]:
data.area.max() == data.area

California    False
Texas          True
New York      False
Florida       False
Illinois      False
Name: area, dtype: bool

In [ ]:
vals2 = np.array([1, np.nan, 3, 4])

In [ ]:
vals2

pd.Series(vals2).isna()



0    False
1     True
2    False
3    False
dtype: bool

In [23]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [26]:
df.fillna(0)

0    1  2
0  1.0  0.0  2
1  2.0  3.0  5
2  0.0  4.0  6

In [28]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [32]:
df.fillna(method='ffill', axis=1)


0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [49]:
dttm = np.arange(24).astype('str')
dttm

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'],
      dtype='<U11')

In [57]:
dttm = np.where(len(str(dttm)) > 1, str(dttm), '0' + str(dttm))
dttm

array('657', dtype='<U4')

In [60]:
import seaborn as sns

In [62]:
titanic = sns.load_dataset('titanic')

In [64]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [66]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
                   'Eric Idle', 'Terry Jones', 'Michael Palin'])

In [70]:
monte

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: object

In [75]:
monte[monte == 'Graham Chapman']

0    Graham Chapman
dtype: object

In [81]:
monte = pd.DataFrame(monte)
monte['salary'] = np.random.randint(100, 200, 6)
monte

0  salary
0  Graham Chapman     107
1     John Cleese     154
2   Terry Gilliam     114
3       Eric Idle     147
4     Terry Jones     194
5   Michael Palin     155

In [84]:
monte.columns = ['name', 'salary']
monte

name  salary
0  Graham Chapman     107
1     John Cleese     154
2   Terry Gilliam     114
3       Eric Idle     147
4     Terry Jones     194
5   Michael Palin     155

In [87]:
monte.loc[monte.name == 'Graham Chapman', 'salary']

0    107
Name: salary, dtype: int32

In [96]:
monte.name.str.split().str.get(0)

monte.name.str.find(' ')


0    6
1    4
2    5
3    4
4    5
5    7
Name: name, dtype: int64

In [105]:
from datetime import datetime


date = datetime.now()
date


datetime.datetime(2022, 7, 10, 14, 32, 31, 821081)

In [107]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

In [110]:
df3 = pd.merge(df1, df2)

In [112]:
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [114]:
df3.shape

(4, 3)

In [116]:
planets = sns.load_dataset('planets')

In [118]:
planets

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [167]:
from enum import unique

# sum(planets.isna().mass)
#planets.groupby('method').std().mass

# planets.loc[~planets.mass.isna(), :]

# planets.loc[~planets.mass.isna(), 'method'].unique()

# planets.mass.fillna(0, inplace=True)

planets

# ~planets.mass.isna()

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507   0.00    172.00  2006
1031          Transit       1        2.615864   0.00    148.00  2007
1032          Transit       1        3.191524   0.00    174.00  2007
1033          Transit       1        4.125083   0.00    293.00  2008
1034          Transit       1        4.187757   0.00    260.00  2008

[1035 rows x 6 columns]

In [209]:
# planets.groupby('method').std().mass < 2

# planets.groupby('method').std().mass.index[planets.groupby('method').std().mass < 2]

# planets.groupby('method').std().mass.index[planets.groupby('method').std().mass < 2]

step1 = planets.groupby('method').std().mass < 2
print(step1)
print('-----------')

step2 = step1.index[step1]
print(step2)
print('-----------')

step3 = planets.loc[planets.method.isin(step2), ["method", "orbital_period"]]
print(step3)
print('-----------')

step4 = step3.groupby('method').mean()
print(step4)



method
Astrometry                        True
Eclipse Timing Variations        False
Imaging                           True
Microlensing                      True
Orbital Brightness Modulation     True
Pulsar Timing                     True
Pulsation Timing Variations      False
Radial Velocity                  False
Transit                           True
Transit Timing Variations         True
Name: mass, dtype: bool
-----------
Index(['Astrometry', 'Imaging', 'Microlensing',
       'Orbital Brightness Modulation', 'Pulsar Timing', 'Transit',
       'Transit Timing Variations'],
      dtype='object', name='method')
-----------
       method  orbital_period
29    Imaging             NaN
30    Imaging             NaN
31    Imaging             NaN
33    Imaging             NaN
34    Imaging             NaN
...       ...             ...
1030  Transit        3.941507
1031  Transit        2.615864
1032  Transit        3.191524
1033  Transit        4.125083
1034  Transit        4.187757

[472

In [211]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [214]:
titanic2 = pd.read_clipboard()

In [216]:
titanic2

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [256]:
titanic3 = pd.read_csv("titanic.csv")


In [257]:
titanic3

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]