In [2]:
import numpy as np

In [3]:
a = np.zeros(10, dtype=np.int16)

In [4]:
b = [0] * 10

In [5]:
a.shape

(10,)

In [6]:
c = np.zeros(9, dtype=np.int16)

In [7]:
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [8]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [9]:
np.full((4,3), 11, dtype=np.int16)
np.ones((4,3))
np.zeros((4,3))

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]], dtype=int16)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.random.seed(0)
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [11]:
x3.shape

(3, 4, 5)

In [12]:
x3[1,1,:][2]

3

In [13]:
x3[1,:,:].shape
x3[1:2,:,:].shape

(4, 5)

(1, 4, 5)

In [14]:
# x3[1,:,:][1,2]
# x3[1:2,:,:][0,1,2]
# x3[1:2,:,:]
# x3[[0, 1],:,:]
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [15]:
x3[0,2,1:4]
x3[1,0,1:4]

array([6, 8, 8])

array([9, 8, 9])

In [16]:
x3[0:2,2,1:4]

array([[6, 8, 8],
       [3, 8, 1]])

In [17]:
x3[0:2,[0,2],1:4][0,1]
x3[0:2,[0,2],1:4][1,0]

array([6, 8, 8])

array([9, 8, 9])

In [18]:
x3[0:2,[0,2],1:4].reshape(-4, 3)[1:3]

array([[6, 8, 8],
       [9, 8, 9]])

In [19]:
x3[0:2,[0,2],1:4]

x3[0:2,[0,2],1:4].reshape(-1, 3)

x3[0:2,[0,2],1:4].reshape(-1, 3)[1:3]

array([[[0, 3, 3],
        [6, 8, 8]],

       [[9, 8, 9],
        [3, 8, 1]]])

array([[0, 3, 3],
       [6, 8, 8],
       [9, 8, 9],
       [3, 8, 1]])

array([[6, 8, 8],
       [9, 8, 9]])

In [20]:
np.ones_like(x3)*100

array([[[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]]])

In [21]:
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [22]:
x4 = x3[1:,1:3,:]
x4

array([[[3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3]],

       [[3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6]]])

In [23]:
x = np.array([1,2,3]).reshape(1,-1)
y = np.array([3,2,1]).reshape(1,-1)
np.concatenate([x,y], axis=0).T.shape

(3, 2)

In [24]:
x = np.array([1,2,3])
y = np.array([3,2,1])

x
y

array([1, 2, 3])

array([3, 2, 1])

In [25]:
np.concatenate([x.reshape(-1,3),y.reshape(-1,3)]).T

array([[1, 3],
       [2, 2],
       [3, 1]])

In [26]:
np.c_[x,y]

array([[1, 3],
       [2, 2],
       [3, 1]])

In [27]:
np.random.seed(0)
x = np.random.randint(1,10,(4,3))
np.random.seed(1)
y = np.random.randint(1,10,(4,3))

x
y

np.c_[x,y]

np.concatenate([x,y], axis=1)

np.concatenate([x,y], axis=0)

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5],
       [8, 7, 9]])

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3]])

array([[6, 1, 4, 6, 9, 6],
       [4, 8, 4, 1, 1, 2],
       [6, 3, 5, 8, 7, 3],
       [8, 7, 9, 5, 6, 3]])

array([[6, 1, 4, 6, 9, 6],
       [4, 8, 4, 1, 1, 2],
       [6, 3, 5, 8, 7, 3],
       [8, 7, 9, 5, 6, 3]])

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5],
       [8, 7, 9],
       [6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3]])

In [28]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))

    print(values)
    print(output)

    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

[6 1 4 4 8]
[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.06810200e-306
 2.33423131e-312]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [29]:
np.random.seed(0)
x = np.random.randint(1,20,1000)

acc = []
s = 0
for i in x:
    s += i
    acc.append(s)




In [30]:
np.add.accumulate(x)

array([  13,   29,   30,   34,   38,   46,   56,   75,   80,   87,  100,
        102,  109,  117,  132,  150,  156,  170,  179,  189,  206,  212,
        228,  244,  245,  264,  268,  286,  301,  309,  310,  312,  322,
        323,  334,  338,  350,  369,  372,  373,  374,  379,  385,  392,
        401,  419,  435,  440,  450,  461,  463,  465,  473,  483,  487,
        494,  506,  521,  540,  541,  556,  560,  573,  584,  596,  601,
        608,  613,  629,  633,  646,  651,  660,  675,  691,  695,  711,
        725,  742,  760,  766,  776,  780,  781,  787,  788,  806,  825,
        830,  833,  850,  854,  857,  868,  882,  899,  907,  917,  918,
        929,  948,  960,  963,  966,  970,  974,  993, 1008, 1012, 1030,
       1049, 1064, 1074, 1076, 1081, 1092, 1104, 1113, 1125, 1128, 1145,
       1146, 1147, 1154, 1169, 1180, 1189, 1203, 1206, 1210, 1213, 1225,
       1239, 1256, 1265, 1274, 1283, 1286, 1290, 1303, 1318, 1319, 1324,
       1328, 1342, 1354, 1368, 1382, 1394, 1411, 14

In [31]:
ser_dir = {'index' + str(i): v for i,v in enumerate(range(10))}

In [32]:
import pandas as pd

In [33]:
ser3 = pd.Series(ser_dir)

In [34]:
ser = pd.Series(data=[100, 200, 300, 400, 500], index=['tom', 'bob', 'nancy', 'dan', 'eric'])
ser

tom      100
bob      200
nancy    300
dan      400
eric     500
dtype: int64

In [35]:
# ser = ser + np.array([10, 20, 30, 40, 50])

ser = (ser *1.1).astype('int')

ser


tom      110
bob      220
nancy    330
dan      440
eric     550
dtype: int32

In [36]:
d = {'one' : pd.Series([100., 200., 300.], 
index=['apple', 'ball', 'clock']),
     'two' : pd.Series([111., 222., 333., 4444.], 
     index=['apple', 'ball', 'cerill', 'dancy'])}

In [37]:
d

{'one': apple    100.0
 ball     200.0
 clock    300.0
 dtype: float64,
 'two': apple      111.0
 ball       222.0
 cerill     333.0
 dancy     4444.0
 dtype: float64}

In [38]:
pd.DataFrame(d)

one     two
apple   100.0   111.0
ball    200.0   222.0
cerill    NaN   333.0
clock   300.0     NaN
dancy     NaN  4444.0

In [39]:
card = pd.read_csv('UCI_Credit_Card.csv')
card.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [40]:
card.iloc[0]

ID                                1.0
LIMIT_BAL                     20000.0
SEX                               2.0
EDUCATION                         2.0
MARRIAGE                          1.0
AGE                              24.0
PAY_0                             2.0
PAY_2                             2.0
PAY_3                            -1.0
PAY_4                            -1.0
PAY_5                            -2.0
PAY_6                            -2.0
BILL_AMT1                      3913.0
BILL_AMT2                      3102.0
BILL_AMT3                       689.0
BILL_AMT4                         0.0
BILL_AMT5                         0.0
BILL_AMT6                         0.0
PAY_AMT1                          0.0
PAY_AMT2                        689.0
PAY_AMT3                          0.0
PAY_AMT4                          0.0
PAY_AMT5                          0.0
PAY_AMT6                          0.0
default.payment.next.month        1.0
Name: 0, dtype: float64

In [41]:
card.describe().LIMIT_BAL['mean']

167484.32266666667

In [42]:
# card.describe().LIMIT_BAL['75%']

# card.loc[:, 'LIMIT_BAL']

# card.loc[:, 'PAY_AMT6'][card.loc[:, 'LIMIT_BAL'] > card.describe().LIMIT_BAL['75%']]

card.loc[card.LIMIT_BAL > card.describe().LIMIT_BAL['75%'],'AGE'].mean()


37.4349794820999

In [43]:
import pandas as pd
import numpy as np

area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [44]:
# 컬럼 추가
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [45]:
data.describe()['pop'].mean()

data.describe()['pop'] < data.describe()['pop'].mean()

data.describe()['density'] > 100


18735074.22255539

count     True
mean     False
std       True
min       True
25%      False
50%      False
75%      False
max      False
Name: pop, dtype: bool

count    False
mean     False
std      False
min      False
25%      False
50%      False
75%       True
max       True
Name: density, dtype: bool

In [46]:
data.loc[(data['density'] > 100) & (data['pop'] < data['pop'].mean()), ['pop']]

pop
New York  19651127
Florida   19552860