In [2]:
import numpy as np
import pandas as pd

In [3]:
data = np.random.randn(100,5)


In [4]:
X = data[:,:-1]


In [5]:
pd.DataFrame(data)

0         1         2         3         4
0   1.415569  0.119675 -0.518148  0.480934  1.198948
1  -0.646145 -0.112640  0.445748  2.202426  1.145878
2   0.122192  0.025512 -2.752577 -0.662179  1.386015
3  -0.309781  0.050979  0.352289  0.028429 -0.803381
4  -0.555104 -2.047758 -0.719115  0.337331  0.245075
..       ...       ...       ...       ...       ...
95  0.979664  0.062335  0.506759 -0.988624  0.079939
96 -0.213690 -0.323729 -0.111581  0.353143 -0.465631
97  0.266728  1.245484  0.031764  0.699571 -0.058412
98 -2.146948  0.714481  1.565391 -0.760855 -0.626029
99 -0.001559 -0.346921 -1.984666  0.120452 -0.866438

[100 rows x 5 columns]

In [6]:
#1. network 설계
#2. predict
#3. loss
#4. loss 미분 --> gradient
#5. grad 값을 network 에 적용 network - gradient * 학습률
#6. 1~5번을 반복

In [11]:
#1
input_layer = np.random.randn(4,7)
layer1 = np.random.randn(7,10)
layer2 = np.random.randn(10,5)
layer3 = np.random.randn(5,10)
output_later = np.random.randn(10,1)

In [8]:
X.shape

(100, 4)

In [9]:
#2

l1 = np.dot(X, input_layer)
l2 = np.dot(l1, layer1)
l3 = np.dot(l2, layer2)
l4 = np.dot(l3, layer3)
y_hat = np.dot(l4, output_later)

In [10]:
#3
def mse(y,t):
    return np.mean((y-t)**2)
    
loss = mse(y_hat,y)    

NameError: name 'y' is not defined

array([-0.83431742,  0.67069162,  0.53745942,  1.42994825,  0.20274364,
        0.868419  , -1.30861999,  1.28297167,  0.74121033,  1.09427505,
        0.65393229, -0.24206121, -2.44305045, -0.24533115, -0.56652032,
        0.92685496,  0.51991628,  1.64681451, -0.68151316,  0.04082856,
        0.1595046 , -1.83688087, -0.1214698 , -0.88535628, -0.47786119,
       -0.32098286, -0.35672736,  0.55946554, -1.6182937 , -0.99326607,
        0.50930598, -0.62601928, -0.88021534,  0.80809323, -0.89570091,
       -0.7704306 ,  0.55249196,  0.7480292 , -0.70482653, -0.24365413,
       -1.26011935, -0.00940958,  1.44436534,  0.55992198, -1.74745956,
       -0.32502987, -0.25150673,  0.48472559, -0.33726506, -0.50234653,
       -0.32037965,  1.39014711,  0.47629653, -0.48881172, -0.29588818,
       -1.45115938, -0.52261497, -0.23193078,  1.31300491,  0.37483235,
        0.34898611, -2.83085031,  1.01885226,  0.5031973 ,  0.8955099 ,
        1.06370051,  2.71414654, -0.75164881,  1.23966927,  0.39

In [ ]:
def gradient(f,x):
    h = 0.0001
    return (f(x+h) - f(x))/h

In [ ]:
def func1(x):
    return 2*(x**2) + 3 * x

In [ ]:
gradient(func1,2)

11.000200000026439

In [ ]:

def func2(x):
    return x[0]**2 + x[1]**2

In [ ]:
func2(np.array([2,3]))

13

In [ ]:
x= np.array([2,3])

for idx in range(x.size):
        print(x[idx])

2
3


In [ ]:
def par_diff(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    for idx in range(x.size):
        tmp_x = x[idx]
        x[idx] = tmp_x + h
        fxh = f(x)
        x[idx] = tmp_x
        fx = f(x)
        grad[idx] = (fxh - fx)/h
    return grad

In [ ]:
x = np.array([2.,3.])
par_diff(func2,x)

array([4.0001, 6.0001])

In [ ]:
def numerical_1d(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    for idx in range(x.size):
        tmp_x = x[idx]
        x[idx] = tmp_x + h
        fxh = f(x)
        x[idx] = tmp_x
        fx = f(x)
        grad[idx]  = (fxh-fx)/h
    return grad

def numerical_2d(f,x):
    h = 1e-4
    grad = np.zeros_like(x)
    for idx, x in enumerate(x):
        grad[idx] = numerical_1d(x)
    return grad


In [ ]:
def numerical_gradient(f,x) :
    h = 1e-4
    grads = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_x = x[idx]
        x[idx] = tmp_x + h
        fxh = f(x)
        x[idx] = tmp_x
        fx = f(x)
        grads[idx]  = (fxh-fx)/h
        it.iternext()
    return grads        

In [ ]:
x = np.array([2.,3.])
numerical_gradient(func2,x)

array([4.0001, 6.0001])