In [2]:
import numpy as np

In [69]:
X = np.random.randn(1000)
a = np.random.randint(10,100,1)
b = np.random.randint(100,300,1)

In [71]:
y = X*a + b
y

array([193.74587968, 160.53892972, 255.17509112, 235.04396288,
       180.3487168 , 207.46861705, 199.02537407, 248.8025109 ,
       220.12774599, 164.58250405, 222.24268717, 164.63366383,
       171.39219248, 144.91327356, 215.13295209, 213.47976295,
       167.2122091 ,  87.33446547,  96.56290105, 227.62511108,
       145.83790067, 246.20205739, 195.70162225, 113.29649902,
       174.10336727, 227.93521171, 173.86226412, 180.04532754,
       220.79314882, 138.08243071, 190.46959685, 276.27902426,
        98.62773318, 264.27215424, 210.79311183, 131.14404611,
       227.00094271, 235.4541472 , 216.58870906, 207.4777309 ,
       204.30822546, 212.64533394, 182.56051053, 206.02854923,
       145.36606265, 192.30982316, 164.72768675, 208.26968401,
       152.67542144, 196.14662845, 199.77376839, 115.55474709,
       151.85555107, 166.41899709, 161.64016894, 280.90972765,
       231.73364491, 126.99313768, 184.89161236, 116.67747916,
       254.79568797, 207.45784307, 109.77759779, 146.76

In [73]:
a_hat = np.random.randn(1)
b_hat = np.random.randn(1)

print(a_hat)
print(b_hat)

[0.04282256]
[0.9228551]


In [74]:
for i in range(10000):
    y_hat = X*a_hat + b_hat
    a_hat = a_hat - 0.001*(X*(y_hat-y)).mean()
    b_hat = b_hat - 0.001*(y_hat-y).mean()
    loss = ((y-y_hat)**2).mean()

In [78]:
a_hat

array([46.00289226])

In [53]:
x1 = np.random.randint(1,100,70)
x2 = np.random.randint(1,100,70)
w1 = np.random.randint(100,1000,1)
w2 = np.random.randint(100,500,1)
b = 10

print(x1)
print(x2)
print(w1)
print(w2)


[61 25 28 31 75 70 45 63 19 85 51 46 98 63 69 90 47 66 25  1 99  4 98 24
 92 44 95 83 86 27 39 87  8 36 69 31 29 46 29  2 79 94 40 31  7 22 70  4
 83 59 92 19 32 84  4 15 18 19 56 60 24 27 51  8 77 17 98 68  2 67]
[ 8  1 27 52  5 14 34 40 19 65 33 37 48 31 95 35 37 88 25  9 58 24 82 50
 13 20 91 25  4 72  9 27 24 34 27 63 20 71 88 81 86 52 20 41 17 63 37 83
 21 58 23 17 51 58 67 34 74 60 86  5  7 63 65 47 14 49 64 64 83 65]
[803]
[130]


In [42]:
y = x1*w1 + x2*w2 + b
y

array([32714, 22004, 11557, 39468, 43964, 37526, 37767, 11540, 70348,
       18142, 67603, 33903, 41494, 24592, 26032, 12705, 62511, 34149,
       53832, 25716, 13284, 37760, 49478, 40898, 33645, 49478, 61317,
       52286, 31404,  9813, 51671, 35606, 31930, 16596, 17983, 38503,
       63167, 44707, 27605, 32048, 14864, 46762, 48535, 62178, 59848,
       59720, 36689,  5968, 14425, 26505,  3112, 47500, 71337, 34706,
       46012, 37205, 57361, 49109, 36091, 39996, 15566, 12985, 32282,
       57607, 41431, 23333, 57279, 17966, 39769,  9017])

In [54]:
X = np.c_[x1,x2]
X.shape

(70, 2)

In [55]:
W = np.concatenate([w1,w2])
W = W.reshape(2,1)
W

array([[803],
       [130]])

In [56]:
y = np.dot(X,W) + b

In [27]:
# np.dot(X,W)
y_hat1 = x1*w1 + x2*w2+b
y_hat2 = np.dot(X,W) + b

In [65]:
w1_hat = np.random.randn(1)
w2_hat = np.random.randn(1)
b_hat = np.random.randn(1)

# W_hat = np.random.randn(2,1)


In [66]:
for i in range(100000):
    # y_hat = x1*w1_hat + x2*w2_hat + b_hat
    # y_hat = np.dot(X,W_hat) + b_hat
    # W_hat = W_hat - 1e-5*(np.dot(X.T,(y_hat-y))).mean()
    # w1_hat = w1_hat - 1e-5*(np.dot(x1,(y_hat-y))).mean()
    # w1_hat = w1_hat - 1e-5*(x1*(y_hat-y)).mean()
    # w2_hat = w2_hat - 1e-5*(x2*(y_hat-y)).mean()
    y_hat = x1*w1_hat + x2*w2_hat + b_hat
    w1_hat = w1_hat - 0.0001*((y_hat-y)*x1).mean()
    w2_hat = w2_hat - 0.0001*((y_hat-y)*x2).mean()
    b_hat = b_hat - 0.0001*(y_hat-y).mean()
    loss = ((y-y_hat)**2).mean()

In [68]:
loss

612217339.5402386

In [86]:
x1 = np.array([0,0,1,1])
x2 = np.array([0,1,0,1])
y_and = np.array([0,0,0,1])

In [81]:
np.c_[x1,x2]

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [158]:
def and_logic(x1,x2):
    w1 = 0.5
    w2 = 1.
    theta = 1.
    return np.where(x1*w1+x2*w2 > theta, 1,0)

In [159]:
and_logic(x1,x2)

array([0, 0, 0, 1])

In [127]:
def or_logic(x1,x2):
    w1 = .1
    w2 = .1
    theta = 0.0
    return np.where(x1*w1+x2*w2 > theta, 1,0)

In [128]:
or_logic(x1,x2)

array([0, 1, 1, 1])

In [122]:
for w1 in np.linspace(0,1,10):
    for w2 in  np.linspace(0,1,10):
        for theta in np.linspace(0,1,10):
            result = np.where(x1*w1+x2*w2 > theta, 1,0)
            if sum(y_and == result) >= 4:
                # print(w1,w2,theta)

IndentationError: expected an indented block (1711453445.py, line 6)

In [124]:
results = []

for w1 in np.linspace(0,1,10):
    for w2 in  np.linspace(0,1,10):
        for theta in np.linspace(0,1,10):
            result = np.where(x1*w1+x2*w2 > theta, 1,0)
            if sum(y_and == result) >= 4:
                results.append((w1,w2,theta))
if len(results) > 0:
    print(f'{len(results)} 개가 존재합니다 {results[0]}')

169 개가 존재합니다 (0.1111111111111111, 0.1111111111111111, 0.1111111111111111)


In [129]:
y_or = np.array([0,1,1,1])

results = []

for w1 in np.linspace(0,1,10):
    for w2 in  np.linspace(0,1,10):
        for theta in np.linspace(0,1,10):
            result = np.where(x1*w1+x2*w2 > theta, 1,0)
            if sum(y_or == result) >= 4:
                results.append((w1,w2,theta))
if len(results) > 0:
    print(f'{len(results)} 개가 존재합니다 {results[0]}')

285 개가 존재합니다 (0.1111111111111111, 0.1111111111111111, 0.0)


In [138]:
y_nand = np.array([1,1,1,0])

results = []

for w1 in np.linspace(0,1,10):
    for w2 in  np.linspace(0,1,10):
        for theta in np.linspace(0,1,10):
            result = np.where(x1*w1+x2*w2 < theta, 1,0)
            if sum(y_nand == result) >= 4:
                results.append((w1,w2,theta))
if len(results) > 0:
    print(f'{len(results)} 개가 존재합니다 {results[0]}')

118 개가 존재합니다 (0.1111111111111111, 0.1111111111111111, 0.2222222222222222)


In [139]:
def nand_logic(x1,x2):
    w1 = .1
    w2 = .1
    theta = .2
    return np.where(x1*w1+x2*w2 < theta, 1,0)

In [141]:
nand_logic(x1,x2)

array([1, 1, 1, 0])

In [143]:
and_logic(x1,x2)

array([0, 0, 0, 1])

In [145]:
y_xor = np.array([0,1,1,0])

results = []

for w1 in np.linspace(0,1,10):
    for w2 in  np.linspace(0,1,10):
        for theta in np.linspace(0,1,10):
            result1 = np.where(x1*w1+x2*w2 < theta, 1,0)
            result2 = np.where(x1*w1+x2*w2 > theta, 1,0)
            if sum(y_xor == result1) >= 4 or sum(y_xor == result2) >= 4:
                results.append((w1,w2,theta))
if len(results) > 0:
    print(f'{len(results)} 개가 존재합니다 {results[0]}')
else:
    print(f'존재하지 않습니다.')    

존재하지 않습니다.


In [146]:
X = np.random.randn(100,20)

In [147]:
y = np.random.randn(100)

In [152]:
layer1 = np.random.randn(20,3)
layer2 = np.random.randn(3,10000)

In [156]:
np.dot(np.dot(X,layer1), layer2).shape

(100, 10000)

In [163]:
x1 = np.array([0,1,0,1])
x2 = np.array([0,0,1,1])
y_xor = np.array([0,1,1,0])

In [164]:
def xor_logic(x1,x2):
    s1 = nand_logic(x1,x2)
    s2 = or_logic(x1,x2)
    return and_logic(s1,s2)

In [165]:
xor_logic(x1,x2)

array([0, 1, 1, 0])